// frontend/src/app/login/page.tsx
import { signIn } from "@/auth";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function LoginPage() {
  return (
    <div className="min-h-dvh flex items-center justify-center bg-background p-4">
      <Card className="w-full max-w-sm p-8 text-center space-y-6">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold">Lab Assistant AI</h1>
          <p className="text-muted-foreground text-sm">
            Inicia sesion para acceder al asistente
          </p>
        </div>

        <form
          action={async () => {
            "use server";
            await signIn("google", { redirectTo: "/" });
          }}
        >
          <Button type="submit" className="w-full" size="lg">
            <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24">
              <path
                d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                fill="#4285F4"
              />
              <path
                d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                fill="#34A853"
              />
              <path
                d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                fill="#FBBC05"
              />
              <path
                d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                fill="#EA4335"
              />
            </svg>
            Iniciar sesion con Google
          </Button>
        </form>

        <p className="text-xs text-muted-foreground">
          Solo usuarios autorizados pueden acceder a esta aplicacion
        </p>
      </Card>
    </div>
  );
}

// frontend-nuxt/app/pages/login.vue
<script setup lang="ts">
definePageMeta({
  layout: false
})

const { loggedIn } = useUserSession()

// Redirect if already logged in
if (loggedIn.value) {
  navigateTo('/')
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 px-4">
    <div class="max-w-md w-full space-y-8">
      <div class="text-center">
        <div class="flex justify-center mb-6">
          <Logo class="h-16 w-auto" />
        </div>
        <h1 class="text-3xl font-bold text-gray-900 dark:text-white">
          Lab Assistant
        </h1>
        <p class="mt-2 text-gray-600 dark:text-gray-400">
          Asistente de IA para laboratorio clínico
        </p>
      </div>

      <div class="mt-8 space-y-4">
        <UButton
          to="/auth/google"
          external
          block
          size="lg"
          color="neutral"
          variant="solid"
          icon="i-simple-icons-google"
          class="justify-center"
        >
          Iniciar sesión con Google
        </UButton>

        <p class="text-center text-sm text-gray-500 dark:text-gray-400">
          Solo usuarios autorizados pueden acceder
        </p>
      </div>
    </div>
  </div>
</template>
